### ISSUE TITLE
README links to ccl

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/dcc-rule-translation#1]
The line in README referring to "General discussion, issues, bugs" is linked to ccl.

It should probably be linked to this repository (https://github.com/corona-warn-app/dcc-rule-translation) instead.

`| **General discussion, issues, bugs**   | <a href="https://github.com/corona-warn-app/cwa-app-ccl/issues/new/choose" title="General Discussion"><img src="https://img.shields.io/github/issues/corona-warn-app/cwa-app-ccl/question.svg?style=flat-square"></a> </a>   |`

**Comment by Ein-Tim** [comment]
I opened #2 to fix this issue.
