### ISSUE TITLE
Wait time increase to 6 months for 1st booster from STIKO 21st recommendations

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/dcc-rule-translation#10]
The 21st STIKO recommendations published on Aug 18, 2022 include a recommended wait of more than 6 months for a first booster vaccination. This is a change from previous recommendations which gave a minimum waiting time of 3 months.

The current booster rules from
https://distribution.dcc-rules.de/bnrules/
viewed using
https://timokoenig.github.io/eu-dcc-rules/?ruleset=de-bn-rules&country=DE

show `BNR-DE-0100` and `BNR-DE-0100` with the text "The German Standing Committee on Vaccinations (STIKO) recommends a booster vaccination for everyone age 12 and older who has not been diagnosed with a SARS-CoV-2 coronavirus infection and who completed their basic immunization more than three months ago."

Is it intended to align `BNR-DE-0100` and `BNR-DE-0100` with the 6 month wait specified by the 21st STIKO recommendations?

## References

- [RKI: COVID-19 und Impfen: Antworten auf häufig gestellte Fragen (FAQ)](https://www.rki.de/SharedDocs/FAQ/COVID-Impfen/gesamt.html)

- [Beschluss der STIKO zur 21. Aktualisierung der COVID-19-Impfempfehlung](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/33/Art_01.html) Stand: 18.08.2022

- [Epidemiologisches Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/33_22.pdf?__blob=publicationFile) Stand: 18.08.2022, Page 10, Table 4

![STIKO 21 Tab 4](https://user-images.githubusercontent.com/66998419/186198084-9cade544-feff-4410-b366-152a12822c5e.jpg)

- [Wissenschaftliche Begründung der STIKO für die Empfehlung zur Verkürzung des Impfabstands zwischen Grundimmunisierung bzw. Infektion und Auffrischimpfung auf einen Zeitraum ab 3 Monate](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/02/Art_02.html) Stand: 13.01.2022

https://github.com/corona-warn-app/dcc-rule-translation/blob/27019b24157c39dc960015f0bab31df352a8143f/i18n/en/strings.xml#L3-L7

**Comment by MikeMcC399** [comment]
@BrittaTSI 

Will somebody be responding to this issue?

**Comment by BrittaTSI** [comment]
@MikeMcC399 - at the moment there is no request from the Bundesgesundheitsministerium to change this.

**Comment by Ein-Tim** [comment]
@BrittaTSI 

Something seems off here & is intransparent. It does not seem like a good process where the Bundesgesundheitsministerium has to act so that rules published by the standing committee on vaccination are updated in the CWA & CovPass. This should be a process which is automatically performed when new recommendations are published.

I don't want to imply anything here, but the changed STIKO recommendations may be against the interests of the BMG.

I will write the BMG a mail giving them a chance to clarify this to me.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

> at the moment there is no request from the Bundesgesundheitsministerium to change this.

Thank you for your feedback! 

I guess it is the responsibility of BMG to give direction for the software rules to be used.

I understood that the STIKO recommendations are legally anchored in § 20 of the Gesetz zur Verhütung und Bekämpfung von Infektionskrankheiten beim Menschen [(Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html)) but perhaps there is no legal responsibility to program the recommendations into the software rules used by CovPass and Corona-Warn-App?

**Comment by BrittaTSI** [comment]
Hi @Ein-Tim & @MikeMcC399,
first of all please keep in mind that we are talking about booster *recommendations* here, i.e. not a mandatory legal requirement to get another shot but just the suggestion that I would be a good idea to do so. Also the CWA (and CovPass) is of course just one of several alternative channels that distribute this information. A lot of people will already have heard about the recommendation in the news or read about it in the paper or on the Internet. CWA and CovPass are supposed provide just another gentle nudge.

Let me get a bit deeper into our collaboration mode. We work according to a process agreeed upon between BMG, RKI, TSI, SAP and IBM. (Unfortunately I am not authorized to share details.) As there are several partners (and in some cases several departments of one of the partners) involved, the process can get lengthy.

Only BMG is authorized to issue a requirement to generate/change/delete a rule. We, the other partners, of course often proactively make suggestions about which rules to implement. However BMG always have the final say, so without their order we cannot start working on a rule.

In the best of all possible worlds BMG and the STIKO (part of RKI) would always agree on which recommendations to issue. In the past there have been conflicting standpoints, though, as you will most probably have learned in the news. Also, not every legal change will result into a new rule. But again - it is up to BMG to decide. We (TSI) are only the contractors that do the implementation.
*edited b/c typos*

**Comment by Ein-Tim** [comment]
@BrittaTSI Thanks for the in-depth explanation of the process!

I hope you understand that my last comment wasn't meant to be an attack against and of the involved parties, but just me questioning the process.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

Thank you once again for providing the background information and explaining about the organization and process!

I do understand that you are acting under contract. From my side the feedback is simply community commentary, noticing some inconsistencies.

The legal definition of full vaccination changes on Oct 1, 2022 to require 3 shots, so then a booster becomes legally significant and it is then a bit more than just a recommendation. See also https://github.com/corona-warn-app/cwa-wishlist/issues/820.

"Ein vollständiger Impfschutz gegen das Coronavirus SARS-CoV-2 liegt vor, wenn"... "insgesamt drei Einzelimpfungen erfolgt sind" ... "(es) liegt ein vollständiger Impfschutz bis zum 30. September 2022 auch bei zwei Einzelimpfungen vor" ...

Since you say that you sometimes make proactive suggestions to BMG, you might have the opportunity to raise this topic with them. As you say, there are other communication channels to citizens, so I will not worry too much if there is no change in the apps. I still think it would be useful to make changes however.

**Comment by MikeMcC399** [comment]
https://www.zusammengegencorona.de/impfen/#id-862101356 from BMG says:

![Impfguide](https://user-images.githubusercontent.com/66998419/187536974-81fa995f-f999-431f-8a1c-f21478d802b8.jpg)

---

CWA 2.25.0 uses old rules and says:

![DE-BNR-0110-DE](https://user-images.githubusercontent.com/66998419/187537740-6b582c32-7712-4a3b-b6e8-e36f116b92df.jpg)

**Comment by MikeMcC399** [comment]
Now that the DE-BNR-0400 rule has been published, with a 6 month wait, 
https://github.com/corona-warn-app/dcc-rule-translation/blob/27019b24157c39dc960015f0bab31df352a8143f/i18n/de/strings.xml#L16-L17

this is inconsistent with DE-BNE-0110 which has only a 3 month wait:
https://github.com/corona-warn-app/dcc-rule-translation/blob/27019b24157c39dc960015f0bab31df352a8143f/i18n/de/strings.xml#L7-L8

It is difficult to understand why there is no initiative to correct DE-BNE-0110 and make the rule consistent with other IT sources of information by changing the wait to 6 months.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

If BMG does not want to align the rules `BNR-DE-0100` and `BNR-DE-0100` with the 6 month wait specified by the 21st STIKO recommendations then I suggest to close this issue.

**Comment by BrittaTSI** [comment]
@MikeMcC399 - I will try to get feedback on this question from BMG in our status call on Monday.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

> I will try to get feedback on this question from BMG in our status call on Monday.

Did you discuss this in your status call? Was there any decision about correcting the text?

**Comment by BrittaTSI** [comment]
> @BrittaTSI
> 
> > I will try to get feedback on this question from BMG in our status call on Monday.
> 
> Did you discuss this in your status call? Was there any decision about correcting the text?

We have addressed this and recommended to align the rule with STIKO's last recommendation. The representative from BMG promised to get back to us. (Hopefully soon.)

**Comment by MikeMcC399** [comment]
@BrittaTSI 

> We have addressed this and recommended to align the rule with STIKO's last recommendation. The representative from BMG promised to get back to us. (Hopefully soon.)

It's good that you recommended change. That is the only sensible action to deal with the incorrect text which the app continues to display (and its associated rule):

![image](https://user-images.githubusercontent.com/66998419/190639977-08f57bce-6dd9-4971-b4b4-130196e69db6.png)

**Comment by BrittaTSI** [comment]
Update - the new version of the Infektionsschutzgesetz (IfSG), valid from October 1th 2022, redefines basic immunization. You will now need at least 3 instances of vaccination or recovery, at least 2 of them vaccination. 
Thus BNR-DE-0100, -0110, -0200 and -0210 will be obsolete and probably deleted altogether.
We are currently working on a new rule (BNR-DE-0500) that will inform users that have only basic immunization now and no booster yet, that they will need to get another shot.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

> ... BNR-DE-0100, -0110, -0200 and -0210 will be obsolete and probably deleted altogether.
We are currently working on a new rule (BNR-DE-0500) that will inform users that have only basic immunization now and no booster yet, that they will need to get another shot.

If the new planned rule (BNR-DE-0500) specifies a wait time in alignment with the current [STIKO recommendations](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/33_22.pdf?__blob=publicationFile) and the other rules are removed, then this issue would be solved.

**Comment by BrittaTSI** [comment]
The new rule will not be an actual notification rule (like the other BNRs) about if and when to get a booster but just an information that you will need another vaccination to complete your basic immunization without mentioning a time frame.
The exact wording is still being finalized by RKI and BMG.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

> The new rule will not be an actual notification rule (like the other BNRs) about if and when to get a booster but just an information that you will need another vaccination to complete your basic immunization without mentioning a time frame. The exact wording is still being finalized by RKI and BMG.

That sounds all right. By now everybody should have received all vaccinations, including boosters if necessary, so a time-frame is not necessary. The important point is that any rule should be in alignment with the current STIKO recommendations.
