### ISSUE TITLE
STIKO name in English BNRs uses "Vaccinations" in plural

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/dcc-rule-translation#11]
## Where to find the issue

https://github.com/corona-warn-app/dcc-rule-translation/blob/main/i18n/en/strings.xml

## Describe the issue

The Booster Notification Rule (BNR) translation into English refers to the STIKO as "The German Standing Committee on Vaccinations (STIKO)" with the word "Vaccinations" in the plural form.

This is not consistent with the name used on the RKI website [Standing Committee on Vaccination (STIKO)](https://www.rki.de/EN/Content/infections/Vaccination/Vaccination_node.html) where "Vaccination" is written in the singular form. (Vanity URL [www.stiko.de/en](http://www.stiko.de/en))

## Suggestion

Change the translated name to "The German Standing Committee on Vaccination (STIKO)" in the BNR rules on https://github.com/corona-warn-app/dcc-rule-translation/blob/main/i18n/en/strings.xml, using the singular form of "Vaccination".

**Comment by InkenTownsend** [comment]
Hello @MikeMcC399 and thank you for your suggestion. 
We checked the issue and found that the plural is also used on other official pages such as https://www.migration-gesundheit.bund.de/en/information-on-the-coronavirus/coronavirus-vaccination and https://www.rki.de/EN/Content/infections/Vaccination/methodology/SOP.pdf?__blob=publicationFile. So as the RKI is not completely consistent on this either and the meaning is not altered by the plural, we think that we can stay with it in the CWA, too. 
Thanks again and kind regards, 
Inken

**Comment by MikeMcC399** [comment]
@InkenTownsend

Unfortunately the DCC rules are not consistent with the CWA website which uses the term "Standing Committee on Vaccination (STIKO)". See the following Blog and FAQ articles:

- https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/ 
- https://www.coronawarn.app/en/faq/results/#vac_cert_booster_info
- https://www.coronawarn.app/en/faq/results/#vac_booster_notification
- https://www.coronawarn.app/en/faq/results/#vac_status

You may want to reconsider your decision in order to make the DCC rule text consistent with the CWA website. I have however already closed the issue since the inconsistency is only minor.
