### ISSUE TITLE
Repository only for CWA?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/dcc-rule-translation#8]
https://github.com/corona-warn-app/dcc-rule-translation/blob/main/README.md says:

"This repository contains the description texts for the booster notification rules to be displayed in the Corona-Warn-App."

Is there a separate repository for the BNR texts used for the CovPass app? I am only aware of the one distribution point https://distribution.dcc-rules.de/bnrules/ so I assume that this is shared by CWA and CovPass.

If the texts from this repository are indeed shared by CWA and CovPass then the [README.md](https://github.com/corona-warn-app/dcc-rule-translation/blob/main/README.md) should be updated to mention also CovPass.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

You answered the question in https://github.com/corona-warn-app/dcc-rule-translation/pull/7#discussion_r950302158 whilst I was writing here. Thank you.

Since you confirmed that only one set of texts are used by both apps, then it would be good to get the README updated.

**Comment by kaddaSz** [comment]
I updated the Readme.

**Comment by MikeMcC399** [comment]
@kaddaSz 

Thank you for updating the README and resolving this issue!
